// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __java_awt_image_DataBufferDouble__
#define __java_awt_image_DataBufferDouble__

#pragma interface

#include <java/awt/image/DataBuffer.h>
#include <gcj/array.h>

extern "Java"
{
  namespace java
  {
    namespace awt
    {
      namespace image
      {
        class DataBufferDouble;
      }
    }
  }
}

class java::awt::image::DataBufferDouble : public ::java::awt::image::DataBuffer
{
public:
  DataBufferDouble (jint);
  DataBufferDouble (jint, jint);
  DataBufferDouble (jdoubleArray, jint);
  DataBufferDouble (jdoubleArray, jint, jint);
  DataBufferDouble (JArray<jdoubleArray> *, jint);
  DataBufferDouble (JArray<jdoubleArray> *, jint, jintArray);
  jdoubleArray getData () { return data; }
  jdoubleArray getData (jint);
  JArray<jdoubleArray> * getBankData () { return bankData; }
  jint getElem (jint);
  jint getElem (jint, jint);
  void setElem (jint, jint);
  void setElem (jint, jint, jint);
  jfloat getElemFloat (jint);
  jfloat getElemFloat (jint, jint);
  void setElemFloat (jint, jfloat);
  void setElemFloat (jint, jint, jfloat);
  jdouble getElemDouble (jint);
  jdouble getElemDouble (jint, jint);
  void setElemDouble (jint, jdouble);
  void setElemDouble (jint, jint, jdouble);
private:
  jdoubleArray __attribute__((aligned(__alignof__( ::java::awt::image::DataBuffer ))))  data;
  JArray<jdoubleArray> * bankData;
public:

  static ::java::lang::Class class$;
};

#endif /* __java_awt_image_DataBufferDouble__ */
