// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_swing_JTable__
#define __javax_swing_JTable__

#pragma interface

#include <javax/swing/JComponent.h>
#include <gcj/array.h>

extern "Java"
{
  namespace java
  {
    namespace awt
    {
      class Rectangle;
      class Dimension;
      class Color;
    }
  }
  namespace javax
  {
    namespace swing
    {
      namespace event
      {
        class TableModelEvent;
        class ListSelectionEvent;
        class ChangeEvent;
        class TableColumnModelEvent;
      }
      class JScrollPane;
      class JTable;
      class ListSelectionModel;
      namespace table
      {
        class TableCellRenderer;
        class JTableHeader;
        class TableModel;
        class TableColumnModel;
        class TableCellEditor;
      }
    }
  }
}

class javax::swing::JTable : public ::javax::swing::JComponent
{
public:
  JTable ();
  JTable (jint, jint);
  JTable (JArray<JArray< ::java::lang::Object *> *> *, JArray< ::java::lang::Object *> *);
  JTable (::javax::swing::table::TableModel *);
  JTable (::javax::swing::table::TableModel *, ::javax::swing::table::TableColumnModel *);
  JTable (::javax::swing::table::TableModel *, ::javax::swing::table::TableColumnModel *, ::javax::swing::ListSelectionModel *);
  JTable (::java::util::Vector *, ::java::util::Vector *);
  static ::javax::swing::JScrollPane *createScrollPaneForTable (::javax::swing::JTable *);
  virtual void clearSelection ();
  virtual void columnAdded (::javax::swing::event::TableColumnModelEvent *);
  virtual void columnMarginChanged (::javax::swing::event::ChangeEvent *);
  virtual void columnMoved (::javax::swing::event::TableColumnModelEvent *);
  virtual void columnRemoved (::javax::swing::event::TableColumnModelEvent *);
  virtual void columnSelectionChanged (::javax::swing::event::ListSelectionEvent *);
public:  // actually protected
  virtual ::javax::swing::table::TableColumnModel *createDefaultColumnModel ();
  virtual ::javax::swing::table::TableModel *createDefaultDataModel ();
  virtual ::javax::swing::ListSelectionModel *createDefaultListSelectionModel ();
public:
  virtual void editingCanceled (::javax::swing::event::ChangeEvent *);
  virtual void editingStopped (::javax::swing::event::ChangeEvent *);
  virtual ::javax::swing::table::TableColumnModel *getColumnModel () { return columnModel; }
  virtual ::javax::swing::table::TableModel *getModel () { return dataModel; }
  virtual ::java::awt::Dimension *getPreferredScrollableViewportSize ();
  virtual jint getScrollableBlockIncrement (::java::awt::Rectangle *, jint, jint);
  virtual jboolean getScrollableTracksViewportHeight ();
  virtual jboolean getScrollableTracksViewportWidth ();
  virtual jint getScrollableUnitIncrement (::java::awt::Rectangle *, jint, jint);
  virtual jint getSelectedRow ();
  virtual ::javax::swing::ListSelectionModel *getSelectionModel ();
  virtual void tableChanged (::javax::swing::event::TableModelEvent *);
  virtual void setModel (::javax::swing::table::TableModel *);
  virtual void setSelectionMode (jint);
  virtual void setSelectionModel (::javax::swing::ListSelectionModel *);
  virtual void setShowGrid (jboolean);
  virtual void valueChanged (::javax::swing::event::ListSelectionEvent *);
  virtual ::javax::swing::table::JTableHeader *getTableHeader () { return tableHeader; }
  virtual void setTableHeader (::javax::swing::table::JTableHeader *);
  virtual jboolean getColumnSelectionAllowed ();
  virtual void setColumnSelectionAllowed (jboolean);
  virtual jboolean getRowSelectionAllowed () { return rowSelectionAllowed; }
  virtual void setRowSelectionAllowed (jboolean);
  virtual jint getAutoResizeMode () { return autoResizeMode; }
  virtual void setAutoResizeMode (jint);
  virtual jint getColumnCount ();
  virtual jint getRowCount ();
  virtual ::javax::swing::table::TableCellRenderer *getCellRenderer (jint, jint);
  virtual ::javax::swing::table::TableCellRenderer *getDefaultRenderer (::java::lang::Class *) { return 0; }
  virtual jint getRowHeight ();
  virtual void setRowHeight (jint);
  virtual void sizeColumnsToFit (jint);
private:
  static const jlong serialVersionUID = 3876025080382781659LL;
public:
  static const jint AUTO_RESIZE_ALL_COLUMNS = 4L;
  static const jint AUTO_RESIZE_LAST_COLUMN = 3L;
  static const jint AUTO_RESIZE_NEXT_COLUMN = 1L;
  static const jint AUTO_RESIZE_OFF = 0L;
  static const jint AUTO_RESIZE_SUBSEQUENT_COLUMNS = 2L;
public:  // actually protected
  jboolean __attribute__((aligned(__alignof__( ::javax::swing::JComponent ))))  autoCreateColumnsFromModel;
  jint autoResizeMode;
  ::javax::swing::table::TableCellEditor *cellEditor;
  jboolean cellSelectionEnabled;
  ::javax::swing::table::TableColumnModel *columnModel;
  ::javax::swing::table::TableModel *dataModel;
  ::java::util::Hashtable *defaultEditorsByColumnClass;
  ::java::util::Hashtable *defaultRenderersByColumnClass;
  jint editingColumn;
  jint editingRow;
  ::java::awt::Color *gridColor;
  ::java::awt::Dimension *preferredViewportSize;
  jint rowHeight;
  jint rowMargin;
  jboolean rowSelectionAllowed;
  ::java::awt::Color *selectionBackground;
  ::java::awt::Color *selectionForeground;
  ::javax::swing::ListSelectionModel *selectionModel;
  jboolean showHorizontalLines;
  jboolean showVerticalLines;
  ::javax::swing::table::JTableHeader *tableHeader;
public:

  static ::java::lang::Class class$;
};

#endif /* __javax_swing_JTable__ */
