// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_swing_JTextField__
#define __javax_swing_JTextField__

#pragma interface

#include <javax/swing/text/JTextComponent.h>
#include <gcj/array.h>

extern "Java"
{
  namespace java
  {
    namespace awt
    {
      class Dimension;
      class Font;
      namespace event
      {
        class ActionListener;
      }
    }
  }
  namespace javax
  {
    namespace swing
    {
      class JTextField;
      namespace text
      {
        class Document;
      }
    }
  }
}

class javax::swing::JTextField : public ::javax::swing::text::JTextComponent
{
public:
  JTextField ();
  JTextField (::java::lang::String *);
  JTextField (jint);
  JTextField (::java::lang::String *, jint);
  JTextField (::javax::swing::text::Document *, ::java::lang::String *, jint);
public:  // actually protected
  virtual ::javax::swing::text::Document *createDefaultModel ();
public:
  virtual ::java::lang::String *getUIClassID ();
  virtual void addActionListener (::java::awt::event::ActionListener *);
  virtual void removeActionListener (::java::awt::event::ActionListener *);
  virtual JArray< ::java::awt::event::ActionListener *> *getActionListeners ();
public:  // actually protected
  virtual void fireActionPerformed ();
public:
  virtual jint getColumns () { return columns; }
  virtual void setColumns (jint);
  virtual jint getHorizontalAlignment () { return align; }
  virtual void setHorizontalAlignment (jint);
  virtual void setFont (::java::awt::Font *);
  virtual ::java::awt::Dimension *getPreferredSize ();
private:
  static const jlong serialVersionUID = 353853209832607592LL;
public:
  static ::java::lang::String *notifyAction;
private:
  jint __attribute__((aligned(__alignof__( ::javax::swing::text::JTextComponent ))))  columns;
  jint align;

  friend class javax_swing_JTextField$AccessibleJTextField;
public:

  static ::java::lang::Class class$;
};

#endif /* __javax_swing_JTextField__ */
