// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_swing_JTextArea__
#define __javax_swing_JTextArea__

#pragma interface

#include <javax/swing/text/JTextComponent.h>

extern "Java"
{
  namespace javax
  {
    namespace swing
    {
      class JTextArea;
      namespace text
      {
        class Document;
      }
    }
  }
}

class javax::swing::JTextArea : public ::javax::swing::text::JTextComponent
{
public:
  JTextArea ();
  JTextArea (::java::lang::String *);
  JTextArea (jint, jint);
  JTextArea (::java::lang::String *, jint, jint);
  JTextArea (::javax::swing::text::Document *);
  JTextArea (::javax::swing::text::Document *, ::java::lang::String *, jint, jint);
  virtual void append (::java::lang::String *);
public:  // actually protected
  virtual ::javax::swing::text::Document *createDefaultModel ();
public:
  virtual jboolean getScrollableTracksViewportWidth ();
  virtual ::java::lang::String *getUIClassID ();
  virtual jint getColumns () { return columns; }
  virtual void setColumns (jint);
  virtual jint getRows () { return rows; }
  virtual void setRows (jint);
  virtual jboolean getLineWrap () { return wrapping; }
  virtual void setLineWrap (jboolean);
  virtual jint getTabSize () { return tabSize; }
  virtual void setTabSize (jint);
  virtual void setWrapStyleWord (jboolean);
private:
  static const jlong serialVersionUID = -6141680179310439825LL;
  jint __attribute__((aligned(__alignof__( ::javax::swing::text::JTextComponent ))))  rows;
  jint columns;
  jboolean wrapping;
  jint tabSize;
public:

  static ::java::lang::Class class$;
};

#endif /* __javax_swing_JTextArea__ */
