// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_swing_JTree__
#define __javax_swing_JTree__

#pragma interface

#include <javax/swing/JComponent.h>
#include <gcj/array.h>

extern "Java"
{
  namespace java
  {
    namespace awt
    {
      class Rectangle;
      class Dimension;
    }
  }
  namespace javax
  {
    namespace accessibility
    {
      class AccessibleContext;
    }
    namespace swing
    {
      class JTree;
      namespace event
      {
        class TreeWillExpandListener;
        class TreeSelectionEvent;
        class TreeSelectionListener;
        class TreeExpansionListener;
      }
      namespace plaf
      {
        class TreeUI;
      }
      namespace tree
      {
        class TreeCellEditor;
        class TreeSelectionModel;
        class TreePath;
        class TreeNode;
        class TreeModel;
        class TreeCellRenderer;
      }
    }
  }
}

class javax::swing::JTree : public ::javax::swing::JComponent
{
public:
  JTree ();
  JTree (::java::util::Hashtable *);
  JTree (JArray< ::java::lang::Object *> *);
  JTree (::javax::swing::tree::TreeModel *);
  JTree (::javax::swing::tree::TreeNode *);
  JTree (::javax::swing::tree::TreeNode *, jboolean);
  JTree (::java::util::Vector *);
public:  // actually protected
  static ::javax::swing::tree::TreeModel *createTreeModel (::java::lang::Object *) { return 0; }
public:
  virtual ::javax::swing::plaf::TreeUI *getUI ();
  virtual void setUI (::javax::swing::plaf::TreeUI *);
  virtual void updateUI ();
  virtual ::java::lang::String *getUIClassID ();
  virtual ::javax::accessibility::AccessibleContext *getAccessibleContext () { return 0; }
  virtual ::java::awt::Dimension *getPreferredScrollableViewportSize () { return 0; }
  virtual jint getScrollableUnitIncrement (::java::awt::Rectangle *, jint, jint);
  virtual jint getScrollableBlockIncrement (::java::awt::Rectangle *, jint, jint);
  virtual jboolean getScrollableTracksViewportWidth ();
  virtual jboolean getScrollableTracksViewportHeight ();
  virtual void addTreeExpansionListener (::javax::swing::event::TreeExpansionListener *);
  virtual void removeTreeExpansionListener (::javax::swing::event::TreeExpansionListener *);
  virtual JArray< ::javax::swing::event::TreeExpansionListener *> *getTreeExpansionListeners ();
  virtual void fireTreeCollapsed (::javax::swing::tree::TreePath *);
  virtual void fireTreeExpanded (::javax::swing::tree::TreePath *);
  virtual void addTreeSelectionListener (::javax::swing::event::TreeSelectionListener *);
  virtual void removeTreeSelectionListener (::javax::swing::event::TreeSelectionListener *);
  virtual JArray< ::javax::swing::event::TreeSelectionListener *> *getTreeSelectionListeners ();
public:  // actually protected
  virtual void fireValueChanged (::javax::swing::event::TreeSelectionEvent *);
public:
  virtual void addTreeWillExpandListener (::javax::swing::event::TreeWillExpandListener *);
  virtual void removeTreeWillExpandListener (::javax::swing::event::TreeWillExpandListener *);
  virtual JArray< ::javax::swing::event::TreeWillExpandListener *> *getTreeWillExpandListeners ();
  virtual void fireTreeWillCollapse (::javax::swing::tree::TreePath *);
  virtual void fireTreeWillExpand (::javax::swing::tree::TreePath *);
  virtual ::javax::swing::tree::TreeModel *getModel () { return treeModel; }
  virtual void setModel (::javax::swing::tree::TreeModel *);
  virtual jboolean isEditable () { return editable; }
  virtual void setEditable (jboolean);
  virtual jboolean isRootVisbile () { return rootVisible; }
  virtual void setRootVisible (jboolean);
  virtual jboolean getShowsRootHandles () { return showsRootHandles; }
  virtual void setShowsRootHandles (jboolean);
  virtual ::javax::swing::tree::TreeCellRenderer *getCellRenderer () { return cellRenderer; }
  virtual void setCellRenderer (::javax::swing::tree::TreeCellRenderer *);
  virtual void collapsePath (::javax::swing::tree::TreePath *);
  virtual void collapseRow (jint);
  virtual void expandPath (::javax::swing::tree::TreePath *);
  virtual void expandRow (jint);
  virtual ::java::lang::Object *getLastSelectedPathComponent ();
  virtual ::javax::swing::tree::TreePath *getPathForLocation (jint, jint);
  virtual ::java::awt::Rectangle *getRowBounds (jint);
  virtual jint getRowCount ();
  virtual ::javax::swing::tree::TreeSelectionModel *getSelectionModel ();
  virtual JArray< ::javax::swing::tree::TreePath *> *getSelectionPaths ();
  virtual jboolean isExpanded (::javax::swing::tree::TreePath *);
  virtual void makeVisible (::javax::swing::tree::TreePath *);
  virtual void scrollPathToVisible (::javax::swing::tree::TreePath *);
  virtual void setCellEditor (::javax::swing::tree::TreeCellEditor *);
  virtual void setLargeModel (jboolean);
  virtual void setRowHeight (jint);
  virtual void setSelectionPath (::javax::swing::tree::TreePath *);
private:
  static const jlong serialVersionUID = 7559816092864483649LL;
public:  // actually protected
  ::javax::swing::tree::TreeCellRenderer * __attribute__((aligned(__alignof__( ::javax::swing::JComponent )))) cellRenderer;
  jboolean editable;
  jboolean rootVisible;
  jboolean showsRootHandles;
  ::javax::swing::tree::TreeModel *treeModel;
public:

  static ::java::lang::Class class$;
};

#endif /* __javax_swing_JTree__ */
