// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_swing_JViewport__
#define __javax_swing_JViewport__

#pragma interface

#include <javax/swing/JComponent.h>
#include <gcj/array.h>

extern "Java"
{
  namespace java
  {
    namespace awt
    {
      class Graphics;
      class Insets;
      class Component;
      class Rectangle;
      class Point;
      class Dimension;
    }
  }
  namespace javax
  {
    namespace swing
    {
      class JViewport;
      namespace event
      {
        class ChangeListener;
        class ChangeEvent;
      }
    }
  }
}

class javax::swing::JViewport : public ::javax::swing::JComponent
{
public:
  JViewport ();
  virtual ::java::awt::Dimension *getExtentSize ();
  virtual ::java::awt::Dimension *toViewCoordinates (::java::awt::Dimension *);
  virtual ::java::awt::Point *toViewCoordinates (::java::awt::Point *);
  virtual void setExtentSize (::java::awt::Dimension *);
  virtual ::java::awt::Dimension *getViewSize ();
  virtual void setViewSize (::java::awt::Dimension *);
  virtual ::java::awt::Point *getViewPosition ();
  virtual void setViewPosition (::java::awt::Point *);
  virtual ::java::awt::Rectangle *getViewRect ();
  virtual jboolean isBackingStoreEnabled ();
  virtual void setBackingStoreEnabled (jboolean);
  virtual void setScrollMode (jint);
  virtual jint getScrollMode () { return scrollMode; }
  virtual ::java::awt::Component *getView ();
  virtual void setView (::java::awt::Component *);
  virtual void revalidate ();
  virtual void reshape (jint, jint, jint, jint);
  virtual void addImpl (::java::awt::Component *, ::java::lang::Object *, jint);
  ::java::awt::Insets *getInsets ();
  ::java::awt::Insets *getInsets (::java::awt::Insets *);
  virtual jboolean isOptimizedDrawingEnabled ();
  virtual JArray< ::javax::swing::event::ChangeListener *> *getChangeListeners ();
  virtual void paint (::java::awt::Graphics *);
public: // actually package-private
  virtual void fireStateChanged ();
public:
  virtual void addChangeListener (::javax::swing::event::ChangeListener *);
  virtual void removeChangeListener (::javax::swing::event::ChangeListener *);
  virtual ::java::lang::String *getUIClassID ();
  virtual void updateUI ();
private:
  static const jlong serialVersionUID = -6925142919680527970LL;
public:
  static const jint SIMPLE_SCROLL_MODE = 0L;
  static const jint BLIT_SCROLL_MODE = 1L;
  static const jint BACKINGSTORE_SCROLL_MODE = 2L;
public: // actually package-private
  ::javax::swing::event::ChangeEvent * __attribute__((aligned(__alignof__( ::javax::swing::JComponent )))) changeEvent;
  jint scrollMode;
public:  // actually protected
  jboolean scrollUnderway;
  jboolean isViewSizeSet;
public: // actually package-private
  ::java::awt::Dimension *extentSize;
  ::java::awt::Dimension *viewSize;
  ::java::awt::Point *lastPaintPosition;
public:

  static ::java::lang::Class class$;
};

#endif /* __javax_swing_JViewport__ */
