// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_swing_RepaintManager__
#define __javax_swing_RepaintManager__

#pragma interface

#include <java/lang/Object.h>

extern "Java"
{
  namespace java
  {
    namespace awt
    {
      class Rectangle;
      class Component;
      class Dimension;
      class Image;
    }
  }
  namespace javax
  {
    namespace swing
    {
      class JComponent;
      class RepaintManager;
      class RepaintManager$RepaintWorker;
    }
  }
}

class javax::swing::RepaintManager : public ::java::lang::Object
{
public:
  RepaintManager ();
  static ::javax::swing::RepaintManager *currentManager (::java::awt::Component *);
  static ::javax::swing::RepaintManager *currentManager (::javax::swing::JComponent *);
  static void setCurrentManager (::javax::swing::RepaintManager *);
  virtual void addInvalidComponent (::javax::swing::JComponent *);
  virtual void removeInvalidComponent (::javax::swing::JComponent *);
  virtual void addDirtyRegion (::javax::swing::JComponent *, jint, jint, jint, jint);
  virtual ::java::awt::Rectangle *getDirtyRegion (::javax::swing::JComponent *);
  virtual void markCompletelyDirty (::javax::swing::JComponent *);
  virtual void markCompletelyClean (::javax::swing::JComponent *);
  virtual jboolean isCompletelyDirty (::javax::swing::JComponent *);
  virtual void validateInvalidComponents ();
  virtual void paintDirtyRegions ();
  virtual ::java::awt::Image *getOffscreenBuffer (::java::awt::Component *, jint, jint);
  virtual ::java::awt::Dimension *getDoubleBufferMaximumSize () { return doubleBufferMaximumSize; }
  virtual void setDoubleBufferMaximumSize (::java::awt::Dimension *);
  virtual void setDoubleBufferingEnabled (jboolean);
  virtual jboolean isDoubleBufferingEnabled () { return doubleBufferingEnabled; }
  virtual ::java::lang::String *toString ();
public: // actually package-private
  ::java::util::Hashtable * __attribute__((aligned(__alignof__( ::java::lang::Object )))) dirtyComponents;
  ::javax::swing::RepaintManager$RepaintWorker *repaintWorker;
  ::java::util::Vector *invalidComponents;
  jboolean doubleBufferingEnabled;
  ::java::awt::Image *doubleBuffer;
  ::java::awt::Dimension *doubleBufferMaximumSize;
private:
  static ::javax::swing::RepaintManager *globalManager;

  friend class javax_swing_RepaintManager$RepaintWorker;
public:

  static ::java::lang::Class class$;
};

#endif /* __javax_swing_RepaintManager__ */
