// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_swing_SwingUtilities__
#define __javax_swing_SwingUtilities__

#pragma interface

#include <java/lang/Object.h>

extern "Java"
{
  namespace java
  {
    namespace awt
    {
      class Frame;
      class Graphics;
      namespace event
      {
        class MouseEvent;
      }
      class Point;
      class Window;
      class Container;
      class FontMetrics;
      class Font;
      class Component;
      class Insets;
      class Rectangle;
    }
  }
  namespace javax
  {
    namespace swing
    {
      class SwingUtilities;
      class Icon;
      class JRootPane;
      class JComponent;
      class SwingUtilities$OwnerFrame;
    }
  }
}

class javax::swing::SwingUtilities : public ::java::lang::Object
{
public:
  static ::java::awt::Rectangle *calculateInsetArea (::java::awt::Rectangle *, ::java::awt::Insets *, ::java::awt::Rectangle *);
  static ::java::awt::Rectangle *calculateInnerArea (::javax::swing::JComponent *, ::java::awt::Rectangle *);
  static ::java::awt::Rectangle *getLocalBounds (::java::awt::Component *);
  static ::java::awt::FontMetrics *getFontMetrics (::java::awt::Font *);
  static ::javax::swing::JRootPane *getRootPane (::java::awt::Component *);
  static ::java::awt::Container *getAncestorNamed (::java::lang::String *, ::java::awt::Component *);
  static ::java::awt::Container *getAncestorOfClass (::java::lang::Class *, ::java::awt::Component *);
  static ::java::awt::Window *windowForComponent (::java::awt::Component *);
  static ::java::awt::Component *getRoot (::java::awt::Component *);
  static jboolean isDescendingFrom (::java::awt::Component *, ::java::awt::Component *);
  static ::java::awt::Component *getDeepestComponentAt (::java::awt::Component *, jint, jint);
  static void convertPointToScreen (::java::awt::Point *, ::java::awt::Component *);
  static void convertPointFromScreen (::java::awt::Point *, ::java::awt::Component *);
  static ::java::awt::Point *convertPoint (::java::awt::Component *, jint, jint, ::java::awt::Component *);
  static ::java::awt::Point *convertPoint (::java::awt::Component *, ::java::awt::Point *, ::java::awt::Component *);
  static ::java::awt::Rectangle *convertRectangle (::java::awt::Component *, ::java::awt::Rectangle *, ::java::awt::Component *);
  static ::java::awt::event::MouseEvent *convertMouseEvent (::java::awt::Component *, ::java::awt::event::MouseEvent *, ::java::awt::Component *);
  static void updateComponentTreeUI (::java::awt::Component *);
  static ::java::lang::String *layoutCompoundLabel (::javax::swing::JComponent *, ::java::awt::FontMetrics *, ::java::lang::String *, ::javax::swing::Icon *, jint, jint, jint, jint, ::java::awt::Rectangle *, ::java::awt::Rectangle *, ::java::awt::Rectangle *, jint);
  static ::java::lang::String *layoutCompoundLabel (::java::awt::FontMetrics *, ::java::lang::String *, ::javax::swing::Icon *, jint, jint, jint, jint, ::java::awt::Rectangle *, ::java::awt::Rectangle *, ::java::awt::Rectangle *, jint);
  static void invokeLater (::java::lang::Runnable *);
  static void invokeAndWait (::java::lang::Runnable *);
  static jboolean isEventDispatchThread ();
  static void paintComponent (::java::awt::Graphics *, ::java::awt::Component *, ::java::awt::Container *, jint, jint, jint, jint);
  static void paintComponent (::java::awt::Graphics *, ::java::awt::Component *, ::java::awt::Container *, ::java::awt::Rectangle *);
public: // actually package-private
  static ::java::awt::Frame *getOwnerFrame ();
public:
  static jboolean isLeftMouseButton (::java::awt::event::MouseEvent *);
  static jboolean isMiddleMouseButton (::java::awt::event::MouseEvent *);
  static jboolean isRightMouseButton (::java::awt::event::MouseEvent *);
  SwingUtilities ();
private:
  static ::javax::swing::SwingUtilities$OwnerFrame *ownerFrame;

  friend class javax_swing_SwingUtilities$OwnerFrame;
public:

  static ::java::lang::Class class$;
};

#endif /* __javax_swing_SwingUtilities__ */
