// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_swing_plaf_basic_BasicRadioButtonUI__
#define __javax_swing_plaf_basic_BasicRadioButtonUI__

#pragma interface

#include <javax/swing/plaf/basic/BasicToggleButtonUI.h>

extern "Java"
{
  namespace javax
  {
    namespace swing
    {
      namespace plaf
      {
        namespace basic
        {
          class BasicRadioButtonUI;
        }
        class ComponentUI;
      }
      class JComponent;
      class Icon;
    }
  }
}

class javax::swing::plaf::basic::BasicRadioButtonUI : public ::javax::swing::plaf::basic::BasicToggleButtonUI
{
public:
  static ::javax::swing::plaf::ComponentUI *createUI (::javax::swing::JComponent *);
  BasicRadioButtonUI ();
  virtual void installUI (::javax::swing::JComponent *);
  virtual ::javax::swing::Icon *getDefaultIcon ();
public:  // actually protected
  ::javax::swing::Icon * __attribute__((aligned(__alignof__( ::javax::swing::plaf::basic::BasicToggleButtonUI )))) icon;
public:

  static ::java::lang::Class class$;
};

#endif /* __javax_swing_plaf_basic_BasicRadioButtonUI__ */
