// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_swing_plaf_basic_BasicListUI__
#define __javax_swing_plaf_basic_BasicListUI__

#pragma interface

#include <javax/swing/plaf/ListUI.h>
#include <gcj/array.h>

extern "Java"
{
  namespace java
  {
    namespace awt
    {
      class Point;
      class Graphics;
      class Dimension;
      class Rectangle;
    }
  }
  namespace javax
  {
    namespace swing
    {
      class ListSelectionModel;
      class ListModel;
      class ListCellRenderer;
      class JComponent;
      class JList;
      namespace plaf
      {
        class ComponentUI;
        namespace basic
        {
          class BasicListUI;
          class BasicListUI$PropertyChangeHandler;
          class BasicListUI$MouseInputHandler;
          class BasicListUI$ListSelectionHandler;
          class BasicListUI$ListDataHandler;
          class BasicListUI$FocusHandler;
        }
      }
    }
  }
}

class javax::swing::plaf::basic::BasicListUI : public ::javax::swing::plaf::ListUI
{
public:
  static ::javax::swing::plaf::ComponentUI *createUI (::javax::swing::JComponent *);
public: // actually package-private
  virtual jint getRowHeight (jint);
public:
  virtual ::java::awt::Rectangle *getCellBounds (::javax::swing::JList *, jint, jint);
public: // actually package-private
  virtual jint convertRowToY (jint);
  virtual jint convertYToRow (jint);
  virtual void updateLayoutState ();
  virtual void damageLayout ();
  virtual void maybeUpdateLayoutState ();
public:
  BasicListUI ();
public: // actually package-private
  virtual void installDefaults ();
  virtual void uninstallDefaults ();
  virtual void installListeners ();
  virtual void uninstallListeners ();
  virtual void installKeyboardActions () { }
  virtual void uninstallKeyboardActions () { }
public:
  virtual void installUI (::javax::swing::JComponent *);
  virtual void uninstallUI (::javax::swing::JComponent *);
  virtual ::java::awt::Dimension *getMaximumSize (::javax::swing::JComponent *);
  virtual ::java::awt::Dimension *getPreferredSize (::javax::swing::JComponent *);
  virtual void paintBackground (::java::awt::Graphics *, ::javax::swing::JComponent *);
public: // actually package-private
  virtual void paintCell (::java::awt::Graphics *, jint, ::java::awt::Rectangle *, ::javax::swing::ListCellRenderer *, ::javax::swing::ListModel *, ::javax::swing::ListSelectionModel *, jint);
public:
  virtual void paint (::java::awt::Graphics *, ::javax::swing::JComponent *);
  virtual jint locationToIndex (::javax::swing::JList *, ::java::awt::Point *);
  virtual ::java::awt::Point *indexToLocation (::javax::swing::JList *, jint);
public: // actually package-private
  ::javax::swing::plaf::basic::BasicListUI$FocusHandler * __attribute__((aligned(__alignof__( ::javax::swing::plaf::ListUI )))) focusListener;
  ::javax::swing::plaf::basic::BasicListUI$ListDataHandler *listDataListener;
  ::javax::swing::plaf::basic::BasicListUI$ListSelectionHandler *listSelectionListener;
  ::javax::swing::plaf::basic::BasicListUI$MouseInputHandler *mouseInputListener;
  ::javax::swing::plaf::basic::BasicListUI$PropertyChangeHandler *propertyChangeListener;
  ::javax::swing::JList *list;
  jint cellHeight;
  jint cellWidth;
  jintArray cellHeights;
  jint updateLayoutStateNeeded;

  friend class javax_swing_plaf_basic_BasicListUI$PropertyChangeHandler;
  friend class javax_swing_plaf_basic_BasicListUI$MouseInputHandler;
  friend class javax_swing_plaf_basic_BasicListUI$ListSelectionHandler;
  friend class javax_swing_plaf_basic_BasicListUI$ListDataHandler;
  friend class javax_swing_plaf_basic_BasicListUI$FocusHandler;
public:

  static ::java::lang::Class class$;
};

#endif /* __javax_swing_plaf_basic_BasicListUI__ */
