// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_swing_plaf_basic_BasicArrowButton__
#define __javax_swing_plaf_basic_BasicArrowButton__

#pragma interface

#include <javax/swing/JButton.h>

extern "Java"
{
  namespace javax
  {
    namespace swing
    {
      namespace plaf
      {
        namespace basic
        {
          class BasicArrowButton;
        }
      }
      namespace border
      {
        class Border;
      }
    }
  }
  namespace java
  {
    namespace awt
    {
      class Polygon;
      class Dimension;
      class Graphics;
      class Color;
    }
  }
}

class javax::swing::plaf::basic::BasicArrowButton : public ::javax::swing::JButton
{
public:
  BasicArrowButton (jint);
  BasicArrowButton (jint, ::java::awt::Color *, ::java::awt::Color *, ::java::awt::Color *, ::java::awt::Color *);
  virtual jint getDirection () { return direction; }
  virtual void setDirection (jint);
  virtual void paint (::java::awt::Graphics *);
  virtual ::java::awt::Dimension *getPreferredSize ();
  virtual ::java::awt::Dimension *getMinimumSize ();
  virtual ::java::awt::Dimension *getMaximumSize ();
  virtual void paintTriangle (::java::awt::Graphics *, jint, jint, jint, jint, jboolean);
private:
  ::java::awt::Polygon *getArrow (jint, jint);
public:  // actually protected
  jint __attribute__((aligned(__alignof__( ::javax::swing::JButton ))))  direction;
private:
  ::java::awt::Color *shadow;
  ::java::awt::Color *darkShadow;
  ::java::awt::Color *highlight;
  ::javax::swing::border::Border *tmpBorder;

  friend class javax_swing_plaf_basic_BasicArrowButton$1;
  friend class javax_swing_plaf_basic_BasicArrowButton$arrowIcon;
public:

  static ::java::lang::Class class$;
};

#endif /* __javax_swing_plaf_basic_BasicArrowButton__ */
