// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_swing_plaf_basic_BasicRootPaneUI__
#define __javax_swing_plaf_basic_BasicRootPaneUI__

#pragma interface

#include <javax/swing/plaf/RootPaneUI.h>

extern "Java"
{
  namespace java
  {
    namespace beans
    {
      class PropertyChangeEvent;
    }
  }
  namespace javax
  {
    namespace swing
    {
      namespace plaf
      {
        namespace basic
        {
          class BasicRootPaneUI;
        }
        class ComponentUI;
      }
      class JComponent;
    }
  }
}

class javax::swing::plaf::basic::BasicRootPaneUI : public ::javax::swing::plaf::RootPaneUI
{
public:
  static ::javax::swing::plaf::ComponentUI *createUI (::javax::swing::JComponent *);
  virtual void installUI (::javax::swing::JComponent *);
  virtual void propertyChange (::java::beans::PropertyChangeEvent *) { }
  BasicRootPaneUI ();

  static ::java::lang::Class class$;
};

#endif /* __javax_swing_plaf_basic_BasicRootPaneUI__ */
