// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_swing_plaf_basic_BasicToggleButtonUI__
#define __javax_swing_plaf_basic_BasicToggleButtonUI__

#pragma interface

#include <javax/swing/plaf/basic/BasicButtonUI.h>

extern "Java"
{
  namespace javax
  {
    namespace swing
    {
      namespace plaf
      {
        namespace basic
        {
          class BasicToggleButtonUI;
        }
        class ComponentUI;
      }
      class JComponent;
    }
  }
}

class javax::swing::plaf::basic::BasicToggleButtonUI : public ::javax::swing::plaf::basic::BasicButtonUI
{
public:
  static ::javax::swing::plaf::ComponentUI *createUI (::javax::swing::JComponent *);
  BasicToggleButtonUI ();

  static ::java::lang::Class class$;
};

#endif /* __javax_swing_plaf_basic_BasicToggleButtonUI__ */
