// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_swing_plaf_basic_BasicOptionPaneUI__
#define __javax_swing_plaf_basic_BasicOptionPaneUI__

#pragma interface

#include <javax/swing/plaf/OptionPaneUI.h>
#include <gcj/array.h>

extern "Java"
{
  namespace javax
  {
    namespace swing
    {
      class Icon;
      namespace plaf
      {
        class ComponentUI;
        namespace basic
        {
          class BasicOptionPaneUI;
          class BasicOptionPaneUI$messageIcon;
        }
      }
      namespace border
      {
        class Border;
      }
      class JOptionPane;
      class JComponent;
    }
  }
  namespace java
  {
    namespace beans
    {
      class PropertyChangeListener;
    }
    namespace awt
    {
      class LayoutManager;
      namespace event
      {
        class ActionListener;
      }
      class GridBagConstraints;
      class Container;
      class Color;
      class Dimension;
      class Component;
    }
  }
}

class javax::swing::plaf::basic::BasicOptionPaneUI : public ::javax::swing::plaf::OptionPaneUI
{
public:
  BasicOptionPaneUI ();
public:  // actually protected
  virtual void addButtonComponents (::java::awt::Container *, JArray< ::java::lang::Object *> *, jint);
  virtual void addIcon (::java::awt::Container *);
private:
  static ::java::awt::GridBagConstraints *createConstraints ();
public:  // actually protected
  virtual void addMessageComponents (::java::awt::Container *, ::java::awt::GridBagConstraints *, ::java::lang::Object *, jint, jboolean);
  virtual void burstStringInto (::java::awt::Container *, ::java::lang::String *, jint);
public:
  virtual jboolean containsCustomComponents (::javax::swing::JOptionPane *) { return hasCustomComponents; }
public:  // actually protected
  virtual ::java::awt::event::ActionListener *createButtonActionListener (jint);
  virtual ::java::awt::Container *createButtonArea ();
  virtual ::java::awt::LayoutManager *createLayoutManager ();
  virtual ::java::awt::Container *createMessageArea ();
  virtual ::java::beans::PropertyChangeListener *createPropertyChangeListener ();
  virtual ::java::awt::Container *createSeparator () { return 0; }
public:
  static ::javax::swing::plaf::ComponentUI *createUI (::javax::swing::JComponent *);
public:  // actually protected
  virtual JArray< ::java::lang::Object *> *getButtons ();
  virtual ::javax::swing::Icon *getIcon ();
  virtual ::javax::swing::Icon *getIconForType (jint);
  virtual jint getInitialValueIndex ();
  virtual jint getMaxCharactersPerLineCount ();
public:
  virtual ::java::awt::Dimension *getMaximumSize (::javax::swing::JComponent *);
public:  // actually protected
  virtual ::java::lang::Object *getMessage ();
public:
  virtual ::java::awt::Dimension *getMinimumOptionPaneSize () { return minimumSize; }
  virtual ::java::awt::Dimension *getMinimumSize (::javax::swing::JComponent *);
  virtual ::java::awt::Dimension *getPreferredSize (::javax::swing::JComponent *);
public:  // actually protected
  virtual jboolean getSizeButtonsToSameWidth ();
  virtual void installComponents ();
  virtual void installDefaults ();
  virtual void installKeyboardActions () { }
  virtual void installListeners ();
public:
  virtual void installUI (::javax::swing::JComponent *);
public:  // actually protected
  virtual void resetInputValue ();
public:
  virtual void selectInitialValue (::javax::swing::JOptionPane *);
private:
  void resetSelectedValue ();
public:  // actually protected
  virtual void uninstallComponents ();
  virtual void uninstallDefaults ();
  virtual void uninstallKeyboardActions () { }
  virtual void uninstallListeners ();
public:
  virtual void uninstallUI (::javax::swing::JComponent *);
public:  // actually protected
  jboolean __attribute__((aligned(__alignof__( ::javax::swing::plaf::OptionPaneUI ))))  hasCustomComponents;
  ::java::awt::Component *initialFocusComponent;
  ::javax::swing::JComponent *inputComponent;
public:
  static jint minimumHeight;
  static jint minimumWidth;
public:  // actually protected
  ::java::awt::Dimension *minimumSize;
  ::java::beans::PropertyChangeListener *propertyChangeListener;
  ::javax::swing::JOptionPane *optionPane;
private:
  static jint iconSize;
  ::java::awt::Color *messageForeground;
  ::javax::swing::border::Border *messageBorder;
  ::javax::swing::border::Border *buttonBorder;
  static ::java::lang::String *OK_STRING;
  static ::java::lang::String *YES_STRING;
  static ::java::lang::String *NO_STRING;
  static ::java::lang::String *CANCEL_STRING;
  ::java::awt::Container *messageAreaContainer;
  ::java::awt::Container *buttonContainer;
  static ::javax::swing::plaf::basic::BasicOptionPaneUI$messageIcon *errorIcon;
  static ::javax::swing::plaf::basic::BasicOptionPaneUI$messageIcon *infoIcon;
  static ::javax::swing::plaf::basic::BasicOptionPaneUI$messageIcon *warningIcon;
  static ::javax::swing::plaf::basic::BasicOptionPaneUI$messageIcon *questionIcon;

  friend class javax_swing_plaf_basic_BasicOptionPaneUI$5;
  friend class javax_swing_plaf_basic_BasicOptionPaneUI$4;
  friend class javax_swing_plaf_basic_BasicOptionPaneUI$3;
  friend class javax_swing_plaf_basic_BasicOptionPaneUI$2;
  friend class javax_swing_plaf_basic_BasicOptionPaneUI$1;
  friend class javax_swing_plaf_basic_BasicOptionPaneUI$messageIcon;
  friend class javax_swing_plaf_basic_BasicOptionPaneUI$PropertyChangeHandler;
  friend class javax_swing_plaf_basic_BasicOptionPaneUI$ButtonAreaLayout;
  friend class javax_swing_plaf_basic_BasicOptionPaneUI$ButtonActionListener;
public:

  static ::java::lang::Class class$;
};

#endif /* __javax_swing_plaf_basic_BasicOptionPaneUI__ */
