// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_swing_plaf_basic_BasicScrollPaneUI__
#define __javax_swing_plaf_basic_BasicScrollPaneUI__

#pragma interface

#include <javax/swing/plaf/ScrollPaneUI.h>

extern "Java"
{
  namespace java
  {
    namespace awt
    {
      class Graphics;
      class Dimension;
    }
  }
  namespace javax
  {
    namespace swing
    {
      class JScrollPane;
      namespace plaf
      {
        namespace basic
        {
          class BasicScrollPaneUI;
        }
        class ComponentUI;
      }
      class JComponent;
    }
  }
}

class javax::swing::plaf::basic::BasicScrollPaneUI : public ::javax::swing::plaf::ScrollPaneUI
{
public:
  static ::javax::swing::plaf::ComponentUI *createUI (::javax::swing::JComponent *);
public:  // actually protected
  virtual void installDefaults (::javax::swing::JScrollPane *);
  virtual void uninstallDefaults (::javax::swing::JScrollPane *);
public:
  virtual void installUI (::javax::swing::JComponent *);
  virtual void uninstallUI (::javax::swing::JComponent *);
  virtual ::java::awt::Dimension *getMinimumSize (::javax::swing::JComponent *);
  virtual ::java::awt::Dimension *getPreferredSize (::javax::swing::JComponent *);
  virtual void paint (::java::awt::Graphics *, ::javax::swing::JComponent *) { }
  BasicScrollPaneUI ();

  static ::java::lang::Class class$;
};

#endif /* __javax_swing_plaf_basic_BasicScrollPaneUI__ */
