// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_swing_plaf_basic_BasicViewportUI__
#define __javax_swing_plaf_basic_BasicViewportUI__

#pragma interface

#include <javax/swing/plaf/ViewportUI.h>

extern "Java"
{
  namespace java
  {
    namespace awt
    {
      class Graphics;
      class Dimension;
      class Image;
    }
  }
  namespace javax
  {
    namespace swing
    {
      namespace plaf
      {
        namespace basic
        {
          class BasicViewportUI;
        }
        class ComponentUI;
      }
      class JComponent;
      namespace event
      {
        class ChangeListener;
      }
    }
  }
}

class javax::swing::plaf::basic::BasicViewportUI : public ::javax::swing::plaf::ViewportUI
{
public: // actually package-private
  virtual void installDefaults (::javax::swing::JComponent *);
  virtual void uninstallDefaults (::javax::swing::JComponent *) { }
  virtual void installListeners (::javax::swing::JComponent *);
  virtual void uninstallListeners (::javax::swing::JComponent *);
public:
  BasicViewportUI ();
  static ::javax::swing::plaf::ComponentUI *createUI (::javax::swing::JComponent *);
  virtual void installUI (::javax::swing::JComponent *);
  virtual void uninstallUI (::javax::swing::JComponent *);
  virtual ::java::awt::Dimension *getPreferredSize (::javax::swing::JComponent *) { return 0; }
  virtual void paint (::java::awt::Graphics *, ::javax::swing::JComponent *);
public: // actually package-private
  ::javax::swing::event::ChangeListener * __attribute__((aligned(__alignof__( ::javax::swing::plaf::ViewportUI )))) changeListener;
  ::java::awt::Image *backingStoreImage;
  jint backingStoreWidth;
  jint backingStoreHeight;

  friend class javax_swing_plaf_basic_BasicViewportUI$ChangeHandler;
public:

  static ::java::lang::Class class$;
};

#endif /* __javax_swing_plaf_basic_BasicViewportUI__ */
