// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __gnu_regexp_CharIndexedStringBuffer__
#define __gnu_regexp_CharIndexedStringBuffer__

#pragma interface

#include <java/lang/Object.h>

extern "Java"
{
  namespace gnu
  {
    namespace regexp
    {
      class CharIndexedStringBuffer;
    }
  }
}

class gnu::regexp::CharIndexedStringBuffer : public ::java::lang::Object
{
public: // actually package-private
  CharIndexedStringBuffer (::java::lang::StringBuffer *, jint);
public:
  virtual jchar charAt (jint);
  virtual jboolean isValid ();
  virtual jboolean move (jint);
private:
  ::java::lang::StringBuffer * __attribute__((aligned(__alignof__( ::java::lang::Object )))) s;
  jint anchor;
public:

  static ::java::lang::Class class$;
};

#endif /* __gnu_regexp_CharIndexedStringBuffer__ */
