// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __gnu_regexp_CharIndexed__
#define __gnu_regexp_CharIndexed__

#pragma interface

#include <java/lang/Object.h>

extern "Java"
{
  namespace gnu
  {
    namespace regexp
    {
      class CharIndexed;
    }
  }
}

class gnu::regexp::CharIndexed : public ::java::lang::Object
{
public:
  virtual jchar charAt (jint) = 0;
  virtual jboolean move (jint) = 0;
  virtual jboolean isValid () = 0;
  static const jint OUT_OF_BOUNDS = 65535L;

  static ::java::lang::Class class$;
} __attribute__ ((java_interface));

#endif /* __gnu_regexp_CharIndexed__ */
