// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __gnu_regexp_CharIndexedString__
#define __gnu_regexp_CharIndexedString__

#pragma interface

#include <java/lang/Object.h>

extern "Java"
{
  namespace gnu
  {
    namespace regexp
    {
      class CharIndexedString;
    }
  }
}

class gnu::regexp::CharIndexedString : public ::java::lang::Object
{
public: // actually package-private
  CharIndexedString (::java::lang::String *, jint);
public:
  virtual jchar charAt (jint);
  virtual jboolean isValid ();
  virtual jboolean move (jint);
private:
  ::java::lang::String * __attribute__((aligned(__alignof__( ::java::lang::Object )))) s;
  jint anchor;
  jint len;
public:

  static ::java::lang::Class class$;
};

#endif /* __gnu_regexp_CharIndexedString__ */
