// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __gnu_regexp_CharIndexedInputStream__
#define __gnu_regexp_CharIndexedInputStream__

#pragma interface

#include <java/lang/Object.h>
#include <gcj/array.h>

extern "Java"
{
  namespace gnu
  {
    namespace regexp
    {
      class CharIndexedInputStream;
    }
  }
}

class gnu::regexp::CharIndexedInputStream : public ::java::lang::Object
{
public: // actually package-private
  CharIndexedInputStream (::java::io::InputStream *, jint);
private:
  jboolean next ();
public:
  virtual jchar charAt (jint);
  virtual jboolean move (jint);
  virtual jboolean isValid ();
private:
  static const jint BUFFER_INCREMENT = 1024L;
  static const jint UNKNOWN = 2147483647L;
  ::java::io::BufferedInputStream * __attribute__((aligned(__alignof__( ::java::lang::Object )))) br;
  jint index;
  jint bufsize;
  jint end;
  jchar cached;
  jcharArray lookBehind;
public:

  static ::java::lang::Class class$;
};

#endif /* __gnu_regexp_CharIndexedInputStream__ */
