// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __gnu_regexp_CharIndexedCharArray__
#define __gnu_regexp_CharIndexedCharArray__

#pragma interface

#include <java/lang/Object.h>
#include <gcj/array.h>

extern "Java"
{
  namespace gnu
  {
    namespace regexp
    {
      class CharIndexedCharArray;
    }
  }
}

class gnu::regexp::CharIndexedCharArray : public ::java::lang::Object
{
public: // actually package-private
  CharIndexedCharArray (jcharArray, jint);
public:
  virtual jchar charAt (jint);
  virtual jboolean isValid ();
  virtual jboolean move (jint);
private:
  jcharArray __attribute__((aligned(__alignof__( ::java::lang::Object ))))  s;
  jint anchor;
public:

  static ::java::lang::Class class$;
};

#endif /* __gnu_regexp_CharIndexedCharArray__ */
