// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __gnu_regexp_REFilterInputStream__
#define __gnu_regexp_REFilterInputStream__

#pragma interface

#include <java/io/FilterInputStream.h>
#include <gcj/array.h>

extern "Java"
{
  namespace gnu
  {
    namespace regexp
    {
      class REFilterInputStream;
      class CharIndexedInputStream;
      class RE;
    }
  }
}

class gnu::regexp::REFilterInputStream : public ::java::io::FilterInputStream
{
public:
  REFilterInputStream (::java::io::InputStream *, ::gnu::regexp::RE *, ::java::lang::String *);
  virtual jint read ();
  virtual jboolean markSupported ();
  virtual jint read (jbyteArray, jint, jint);
  virtual jint read (jbyteArray);
private:
  ::gnu::regexp::RE * __attribute__((aligned(__alignof__( ::java::io::FilterInputStream )))) expr;
  ::java::lang::String *replace;
  ::java::lang::String *buffer;
  jint bufpos;
  jint offset;
  ::gnu::regexp::CharIndexedInputStream *stream;
public:

  static ::java::lang::Class class$;
};

#endif /* __gnu_regexp_REFilterInputStream__ */
