// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __gnu_regexp_REMatch__
#define __gnu_regexp_REMatch__

#pragma interface

#include <java/lang/Object.h>
#include <gcj/array.h>

extern "Java"
{
  namespace gnu
  {
    namespace regexp
    {
      class CharIndexed;
      class REMatch;
    }
  }
}

class gnu::regexp::REMatch : public ::java::lang::Object
{
public:
  ::java::lang::Object *clone ();
public: // actually package-private
  void assignFrom (::gnu::regexp::REMatch *);
  REMatch (jint, jint, jint);
  void finish (::gnu::regexp::CharIndexed *);
  void clear (jint);
public:
  ::java::lang::String *toString () { return matchedText; }
  jint getStartIndex ();
  jint getEndIndex ();
  ::java::lang::String *toString (jint);
  jint getSubStartIndex (jint);
  jint getStartIndex (jint);
  jint getSubEndIndex (jint);
  jint getEndIndex (jint);
  ::java::lang::String *substituteInto (::java::lang::String *);
private:
  ::java::lang::String * __attribute__((aligned(__alignof__( ::java::lang::Object )))) matchedText;
public: // actually package-private
  jint eflags;
  jint offset;
  jint anchor;
  jint index;
  jintArray start;
  jintArray end;
  ::gnu::regexp::REMatch *next;
public:

  static ::java::lang::Class class$;
};

#endif /* __gnu_regexp_REMatch__ */
