// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __gnu_regexp_RETokenStart__
#define __gnu_regexp_RETokenStart__

#pragma interface

#include <gnu/regexp/REToken.h>

extern "Java"
{
  namespace gnu
  {
    namespace regexp
    {
      class RETokenStart;
      class REMatch;
      class CharIndexed;
    }
  }
}

class gnu::regexp::RETokenStart : public ::gnu::regexp::REToken
{
public: // actually package-private
  RETokenStart (jint, ::java::lang::String *);
  virtual jboolean match (::gnu::regexp::CharIndexed *, ::gnu::regexp::REMatch *);
  virtual void dump (::java::lang::StringBuffer *);
private:
  ::java::lang::String * __attribute__((aligned(__alignof__( ::gnu::regexp::REToken )))) newline;
public:

  static ::java::lang::Class class$;
};

#endif /* __gnu_regexp_RETokenStart__ */
