// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __gnu_regexp_RETokenBackRef__
#define __gnu_regexp_RETokenBackRef__

#pragma interface

#include <gnu/regexp/REToken.h>

extern "Java"
{
  namespace gnu
  {
    namespace regexp
    {
      class RETokenBackRef;
      class REMatch;
      class CharIndexed;
    }
  }
}

class gnu::regexp::RETokenBackRef : public ::gnu::regexp::REToken
{
public: // actually package-private
  RETokenBackRef (jint, jint, jboolean);
  jboolean match (::gnu::regexp::CharIndexed *, ::gnu::regexp::REMatch *);
  void dump (::java::lang::StringBuffer *);
private:
  jint __attribute__((aligned(__alignof__( ::gnu::regexp::REToken ))))  num;
  jboolean insens;
public:

  static ::java::lang::Class class$;
};

#endif /* __gnu_regexp_RETokenBackRef__ */
