// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __gnu_regexp_RETokenOneOf__
#define __gnu_regexp_RETokenOneOf__

#pragma interface

#include <gnu/regexp/REToken.h>

extern "Java"
{
  namespace gnu
  {
    namespace regexp
    {
      class RETokenOneOf;
      class REMatch;
      class CharIndexed;
    }
  }
}

class gnu::regexp::RETokenOneOf : public ::gnu::regexp::REToken
{
public: // actually package-private
  RETokenOneOf (jint, ::java::lang::String *, jboolean, jboolean);
  RETokenOneOf (jint, ::java::util::Vector *, jboolean);
  jint getMinimumLength ();
  jboolean match (::gnu::regexp::CharIndexed *, ::gnu::regexp::REMatch *);
  void dump (::java::lang::StringBuffer *);
private:
  ::java::util::Vector * __attribute__((aligned(__alignof__( ::gnu::regexp::REToken )))) options;
  jboolean negative;
public:

  static ::java::lang::Class class$;
};

#endif /* __gnu_regexp_RETokenOneOf__ */
