// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __gnu_regexp_RETokenEndSub__
#define __gnu_regexp_RETokenEndSub__

#pragma interface

#include <gnu/regexp/REToken.h>

extern "Java"
{
  namespace gnu
  {
    namespace regexp
    {
      class RETokenEndSub;
      class REMatch;
      class CharIndexed;
    }
  }
}

class gnu::regexp::RETokenEndSub : public ::gnu::regexp::REToken
{
public: // actually package-private
  RETokenEndSub (jint);
  jboolean match (::gnu::regexp::CharIndexed *, ::gnu::regexp::REMatch *);
  void dump (::java::lang::StringBuffer *) { }
public:

  static ::java::lang::Class class$;
};

#endif /* __gnu_regexp_RETokenEndSub__ */
