// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __gnu_regexp_RETokenAny__
#define __gnu_regexp_RETokenAny__

#pragma interface

#include <gnu/regexp/REToken.h>

extern "Java"
{
  namespace gnu
  {
    namespace regexp
    {
      class RETokenAny;
      class REMatch;
      class CharIndexed;
    }
  }
}

class gnu::regexp::RETokenAny : public ::gnu::regexp::REToken
{
public: // actually package-private
  RETokenAny (jint, jboolean, jboolean);
  jint getMinimumLength ();
  jboolean match (::gnu::regexp::CharIndexed *, ::gnu::regexp::REMatch *);
  void dump (::java::lang::StringBuffer *);
private:
  jboolean __attribute__((aligned(__alignof__( ::gnu::regexp::REToken ))))  newline;
  jboolean matchNull;
public:

  static ::java::lang::Class class$;
};

#endif /* __gnu_regexp_RETokenAny__ */
