// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __gnu_regexp_RETokenWordBoundary__
#define __gnu_regexp_RETokenWordBoundary__

#pragma interface

#include <gnu/regexp/REToken.h>

extern "Java"
{
  namespace gnu
  {
    namespace regexp
    {
      class RETokenWordBoundary;
      class REMatch;
      class CharIndexed;
    }
  }
}

class gnu::regexp::RETokenWordBoundary : public ::gnu::regexp::REToken
{
public: // actually package-private
  RETokenWordBoundary (jint, jint, jboolean);
  jboolean match (::gnu::regexp::CharIndexed *, ::gnu::regexp::REMatch *);
  void dump (::java::lang::StringBuffer *);
private:
  jboolean __attribute__((aligned(__alignof__( ::gnu::regexp::REToken ))))  negated;
  jint where;
public: // actually package-private
  static const jint BEGIN = 1L;
  static const jint END = 2L;
public:

  static ::java::lang::Class class$;
};

#endif /* __gnu_regexp_RETokenWordBoundary__ */
