// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __gnu_regexp_RETokenRange__
#define __gnu_regexp_RETokenRange__

#pragma interface

#include <gnu/regexp/REToken.h>

extern "Java"
{
  namespace gnu
  {
    namespace regexp
    {
      class RETokenRange;
      class REMatch;
      class CharIndexed;
    }
  }
}

class gnu::regexp::RETokenRange : public ::gnu::regexp::REToken
{
public: // actually package-private
  RETokenRange (jint, jchar, jchar, jboolean);
  jint getMinimumLength ();
  jboolean match (::gnu::regexp::CharIndexed *, ::gnu::regexp::REMatch *);
  void dump (::java::lang::StringBuffer *);
private:
  jchar __attribute__((aligned(__alignof__( ::gnu::regexp::REToken ))))  lo;
  jchar hi;
  jboolean insens;
public:

  static ::java::lang::Class class$;
};

#endif /* __gnu_regexp_RETokenRange__ */
