// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __gnu_regexp_RETokenPOSIX__
#define __gnu_regexp_RETokenPOSIX__

#pragma interface

#include <gnu/regexp/REToken.h>
#include <gcj/array.h>

extern "Java"
{
  namespace gnu
  {
    namespace regexp
    {
      class RETokenPOSIX;
      class REMatch;
      class CharIndexed;
    }
  }
}

class gnu::regexp::RETokenPOSIX : public ::gnu::regexp::REToken
{
public: // actually package-private
  static jint intValue (::java::lang::String *);
  RETokenPOSIX (jint, jint, jboolean, jboolean);
  jint getMinimumLength ();
  jboolean match (::gnu::regexp::CharIndexed *, ::gnu::regexp::REMatch *);
  void dump (::java::lang::StringBuffer *);
  jint __attribute__((aligned(__alignof__( ::gnu::regexp::REToken ))))  type;
  jboolean insens;
  jboolean negated;
  static const jint ALNUM = 0L;
  static const jint ALPHA = 1L;
  static const jint BLANK = 2L;
  static const jint CNTRL = 3L;
  static const jint DIGIT = 4L;
  static const jint GRAPH = 5L;
  static const jint LOWER = 6L;
  static const jint PRINT = 7L;
  static const jint PUNCT = 8L;
  static const jint SPACE = 9L;
  static const jint UPPER = 10L;
  static const jint XDIGIT = 11L;
  static JArray< ::java::lang::String *> *s_nameTable;
public:

  static ::java::lang::Class class$;
};

#endif /* __gnu_regexp_RETokenPOSIX__ */
