// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __gnu_regexp_REToken__
#define __gnu_regexp_REToken__

#pragma interface

#include <java/lang/Object.h>

extern "Java"
{
  namespace gnu
  {
    namespace regexp
    {
      class REMatch;
      class CharIndexed;
      class REToken;
    }
  }
}

class gnu::regexp::REToken : public ::java::lang::Object
{
public:  // actually protected
  REToken (jint);
public: // actually package-private
  virtual jint getMinimumLength ();
  virtual void setUncle (::gnu::regexp::REToken *);
  virtual jboolean match (::gnu::regexp::CharIndexed *, ::gnu::regexp::REMatch *) = 0;
public:  // actually protected
  virtual jboolean next (::gnu::regexp::CharIndexed *, ::gnu::regexp::REMatch *);
public: // actually package-private
  virtual jboolean chain (::gnu::regexp::REToken *);
  virtual void dump (::java::lang::StringBuffer *) = 0;
  virtual void dumpAll (::java::lang::StringBuffer *);
public:  // actually protected
  ::gnu::regexp::REToken * __attribute__((aligned(__alignof__( ::java::lang::Object )))) next__;
  ::gnu::regexp::REToken *uncle;
  jint subIndex;
public:

  static ::java::lang::Class class$;
};

#endif /* __gnu_regexp_REToken__ */
