// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __gnu_regexp_RETokenChar__
#define __gnu_regexp_RETokenChar__

#pragma interface

#include <gnu/regexp/REToken.h>
#include <gcj/array.h>

extern "Java"
{
  namespace gnu
  {
    namespace regexp
    {
      class RETokenChar;
      class REToken;
      class REMatch;
      class CharIndexed;
    }
  }
}

class gnu::regexp::RETokenChar : public ::gnu::regexp::REToken
{
public: // actually package-private
  RETokenChar (jint, jchar, jboolean);
  jint getMinimumLength ();
  jboolean match (::gnu::regexp::CharIndexed *, ::gnu::regexp::REMatch *);
  jboolean chain (::gnu::regexp::REToken *);
  void dump (::java::lang::StringBuffer *);
private:
  jcharArray __attribute__((aligned(__alignof__( ::gnu::regexp::REToken ))))  ch;
  jboolean insens;
public:

  static ::java::lang::Class class$;
};

#endif /* __gnu_regexp_RETokenChar__ */
