// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __gnu_regexp_UncheckedRE__
#define __gnu_regexp_UncheckedRE__

#pragma interface

#include <gnu/regexp/RE.h>

extern "Java"
{
  namespace gnu
  {
    namespace regexp
    {
      class UncheckedRE;
      class RESyntax;
    }
  }
}

class gnu::regexp::UncheckedRE : public ::gnu::regexp::RE
{
public:
  UncheckedRE (::java::lang::Object *);
  UncheckedRE (::java::lang::Object *, jint);
  UncheckedRE (::java::lang::Object *, jint, ::gnu::regexp::RESyntax *);

  static ::java::lang::Class class$;
};

#endif /* __gnu_regexp_UncheckedRE__ */
