// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_swing_text_FieldView__
#define __javax_swing_text_FieldView__

#pragma interface

#include <javax/swing/text/PlainView.h>

extern "Java"
{
  namespace java
  {
    namespace awt
    {
      class Shape;
      class Graphics;
      class FontMetrics;
    }
  }
  namespace javax
  {
    namespace swing
    {
      namespace text
      {
        class FieldView;
        class Element;
      }
    }
  }
}

class javax::swing::text::FieldView : public ::javax::swing::text::PlainView
{
public:
  FieldView (::javax::swing::text::Element *);
public:  // actually protected
  virtual ::java::awt::FontMetrics *getFontMetrics ();
public:
  virtual jfloat getPreferredSpan (jint);
  virtual jint getResizeWeight (jint);
  virtual void paint (::java::awt::Graphics *, ::java::awt::Shape *);

  static ::java::lang::Class class$;
};

#endif /* __javax_swing_text_FieldView__ */
