// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_swing_text_PlainView__
#define __javax_swing_text_PlainView__

#pragma interface

#include <javax/swing/text/View.h>

extern "Java"
{
  namespace javax
  {
    namespace swing
    {
      namespace text
      {
        class PlainView;
        class Element;
      }
    }
  }
  namespace java
  {
    namespace awt
    {
      class Shape;
      class Graphics;
      class FontMetrics;
    }
  }
}

class javax::swing::text::PlainView : public ::javax::swing::text::View
{
public:
  PlainView (::javax::swing::text::Element *);
  virtual void drawLine (jint, ::java::awt::Graphics *, jint, jint);
  virtual jint drawSelectedText (::java::awt::Graphics *, jint, jint, jint, jint);
  virtual jint drawUnselectedText (::java::awt::Graphics *, jint, jint, jint, jint);
  virtual void paint (::java::awt::Graphics *, ::java::awt::Shape *);
  virtual jint getTabSize ();
  virtual jfloat nextTabStop (jfloat, jint);
  virtual jfloat getPreferredSpan (jint);
public:  // actually protected
  ::java::awt::FontMetrics * __attribute__((aligned(__alignof__( ::javax::swing::text::View )))) metrics;
public:

  static ::java::lang::Class class$;
};

#endif /* __javax_swing_text_PlainView__ */
